### ISSUE TITLE
不能联机吗？

### ISSUE THREAD

**Issue by hatrd** [fe11n/ElainaInSpire#48]
我联机功能呢？

Mods in stacktrace:
 - ElainaMod (0.0.1)
Cause:
java.lang.ClassCastException: spireTogether.monsters.playerChars.NetworkDefaultChar cannot be cast to com.megacrit.cardcrawl.characters.AbstractPlayer
	at ElainaMod.powers.ResidualMagicPower.atStartOfTurn(ResidualMagicPower.java:52)
	at com.megacrit.cardcrawl.core.AbstractCreature.applyStartOfTurnPowers(AbstractCreature.java:612)
	at com.megacrit.cardcrawl.monsters.MonsterGroup.applyPreTurnLogic(MonsterGroup.java:133)
	at com.megacrit.cardcrawl.actions.common.MonsterStartTurnAction.update(MonsterStartTurnAction.java:22)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by fe11n** [comment]
别急
